server:
  port: 8761

ead:
  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka'

