server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
      - id: ead-authuser
        uri: lb://EAD-AUTHUSER
        predicates:
          - Path=/ead-authuser/**
      - id: ead-course
        uri: lb://EAD-COURSE
        predicates:
          - Path=/ead-course/**
      - id: ead-notification
        uri: lb://EAD-NOTIFICATION
        predicates:
          - Path=/ead-notification/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost