server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
      - id: ead-authuser
        uri: lb://EAD-AUTHUSER
        predicates:
          - Path=/ead-authuser/**
      - id: ead-course
        uri: lb://EAD-COURSE
        predicates:
          - Path=/ead-course/**
      - id: ead-notification
        uri: lb://EAD-NOTIFICATION
        predicates:
          - Path=/ead-notification/**

ead:
  serviceRegistry:
    username: serviceregistry
    password: ead123sr

eureka:
  client:
    serviceUrl:
      defaultZone: http://${ead.serviceRegistry.username}:${ead.serviceRegistry.password}@localhost:8761/eureka
  instance:
    hostname: localhost