server:
  port: 8080

spring:
  application:
    name: ead-api-gateway
  cloud:
    gateway:
      routes:
      - id: ead-authuser
        uri: http://localhost:8087/
        predicates:
          - Path=/ead-authuser/**
      - id: ead-course
        uri: http://localhost:8082/
        predicates:
          - Path=/ead-course/**
